import React,{useState} from 'react';
import {ArrowUpRight,ArrowRight,Check,Plus,Layers,Play,RotateCcw,Download,Command,ChevronRight} from 'lucide-react';
import tokens from '../AwesomeDS/tokens.json';

const profiles=tokens.profiles;
const studies=[
 ['01','Apple','文字の階層と拡大への対応','文字サイズを変えても、読む順番と操作を保つ。','https://developer.apple.com/videos/play/wwdc2024/10074/'],
 ['02','Google','強弱をつける色・形・サイズ','目立たせる要素を選び、次の操作を明確にする。','https://design.google/library/expressive-material-design-google-research'],
 ['03','Nothing','製品の特徴を中心にした構成','製品の機能と、その使い方を近くに配置する。','https://us.nothing.tech/'],
 ['04','Goodpatch','標準とブランド拡張の両立','原則・ガイドライン・実装を同じ基盤で管理する。','https://sparkle-design.goodpatch.com/'],
 ['05','Duolingo','利用者に近づく設計プロセス','見た目の評価に加え、利用者の目的から判断する。','https://blog.duolingo.com/duologues-design-conversations/'],
 ['06','UI Skills','細部を検証できるルール','角丸の関係や状態変化を、実画面で確かめる。','https://www.ui-skills.com/skills/jakubkrehel/better-ui'],
];
function ProjectPreview(){const [done,setDone]=useState([true,false,false]);return <div className="project-preview"><div className="preview-toolbar"><span><Layers size={18}/> Workspace</span><span className="sample-tag">操作デモ</span></div><div className="project-body"><div className="spread"><span className="eyebrow">PROJECT / 012</span><span className="project-avatars">YK</span></div><h3>Webサイトのリニューアル</h3><p>公開に向けたタスクを確認します。</p><div className="project-progress"><span>完了したタスク</span><b>{done.filter(Boolean).length} / 3</b></div><div className="progress-track" role="progressbar" aria-label="完了したタスク" aria-valuenow={done.filter(Boolean).length} aria-valuemin={0} aria-valuemax={3}><span style={{width:`${done.filter(Boolean).length/3*100}%`}}/></div><div className="task-list">{['ページ構成を決める','デザインをレビューする','公開前の動作を確認する'].map((label,i)=><label key={label}><input type="checkbox" checked={done[i]} onChange={()=>setDone(done.map((v,n)=>n===i?!v:v))}/><span>{label}</span><small>{done[i]?'完了':i===1?'進行中':'未着手'}</small></label>)}</div><div className="project-foot"><span aria-live="polite">{done.every(Boolean)?'すべてのタスクが完了しました':'タスクを押して進捗を変更'}</span><button aria-label="タスクの状態をリセット" className="icon-button" onClick={()=>setDone([true,false,false])}><RotateCcw size={17}/></button></div></div></div>}
function StudioPreview(){const [view,setView]=useState(0);return <div className="studio-preview"><div className="preview-toolbar"><b>FORM / OBJECTS</b><span className="sample-tag">構成デモ</span></div><div className={'object-composition object-'+view} aria-hidden="true"><div className="object-disc"/><div className="object-pillar"/><div className="object-plinth"/></div><div className="studio-bottom"><div><span className="eyebrow">COLLECTION {String(view+1).padStart(2,'0')}</span><h3>{['形と素材','光と陰影','面と奥行き'][view]}</h3></div><button className="sample-action" onClick={()=>setView((view+1)%3)} aria-label="次の構成を見る"><ArrowRight size={24}/></button></div></div>}
function LearnPreview(){const [answer,setAnswer]=useState(null);return <div className="learn-preview"><div className="preview-toolbar"><b>DESIGN PRACTICE</b><span className="sample-tag">学習デモ</span></div><div className="lesson-content"><div className="lesson-symbol" aria-hidden="true"><Check size={42}/></div><span className="eyebrow">LESSON 01 / アクセシビリティ</span><h3>エラーを伝えるとき、<br/>どちらが適切？</h3>{['入力欄を赤くするだけ','理由と修正方法も表示する'].map((v,i)=><button key={v} aria-pressed={answer===i} className={'answer '+(answer===i?'chosen':'')} onClick={()=>setAnswer(i)}><span>{String(i+1).padStart(2,'0')}</span>{v}{answer===i&&<Check size={18}/>}</button>)}<p role="status">{answer===null?'回答を選択してください。':answer===1?'正解です。色の違いだけに意味を任せません。':'色だけでは伝わらない場合があります。もう一度選んでみてください。'}</p></div></div>}
function BrandLab(){const [profile,setProfile]=useState('work');const p=profiles[profile];const explanations={work:'繰り返す操作を優先。進捗とタスクを同じ領域にまとめ、一覧の密度を保ちます。',studio:'作品の形を大きく見せる構成。直線的な形と広い余白で、情報の強弱をつけます。',learn:'選択肢を押しやすく配置。回答の直後に理由を示し、その場でやり直せるようにします。'};function download(){const url=URL.createObjectURL(new Blob([JSON.stringify({baseVersion:tokens.version,profile,...p},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`awesomeds-${profile}.json`;a.click();URL.revokeObjectURL(url)}return <section className="brand-lab" id="brand-lab"><div className="lab-heading"><div><span className="eyebrow">01 / LIVE DESIGN SYSTEM</span><h2>用途に合わせた<br/>デザインを試す</h2></div><p>操作性の基準を共有しながら、<br/>目的に合わせて画面の構成と表現を変える。</p></div><div className="lab-shell"><div className="lab-settings"><span className="eyebrow">用途を選択</span><div className="profile-options">{Object.entries(profiles).map(([id,v],i)=><button key={id} aria-pressed={profile===id} onClick={()=>setProfile(id)}><span>0{i+1}</span><div><b>{v.label}</b><small>{['WORKSPACE','BRAND / EDITORIAL','LEARNING'][i]}</small></div><ArrowUpRight size={18}/></button>)}</div><div className="profile-reason" aria-live="polite"><span className="eyebrow">この構成を選んだ理由</span><p>{explanations[profile]}</p></div><dl className="profile-tokens"><div><dt>アクセント</dt><dd><i style={{background:p.accent}}/>{p.accent}</dd></div><div><dt>角丸</dt><dd>{p.radius} px</dd></div><div><dt>基準の間隔</dt><dd>{p.gap} px</dd></div></dl><button className="quiet" onClick={download}><Download size={16}/>この設定を保存</button></div><div className="lab-canvas" style={{'--sample-accent':p.accent,'--sample-on':p.onAccent,'--sample-radius':p.radius+'px','--sample-gap':p.gap+'px',background:p.canvas}}><div className="canvas-coordinate" aria-hidden="true">AWESOME DS / {profile.toUpperCase()}</div><div className="sample-frame" key={profile}>{profile==='work'?<ProjectPreview/>:profile==='studio'?<StudioPreview/>:<LearnPreview/>}</div><span className="canvas-caption">独自に制作した実装例 · ブランドの複製ではありません</span></div></div><div className="lab-note"><span>共通の基準</span><p>44px以上の操作領域 / キーボード操作 / 明確な状態表示 / 動きを減らす設定</p></div></section>}
function RadiusStudy(){const [padding,setPadding]=useState(12);return <section className="radius-study"><div className="radius-copy"><span className="eyebrow">02 / DESIGN DETAIL</span><h2>余白に合わせて<br/>角丸を調整する</h2><p>外側と内側に同じ角丸を指定すると、角付近の余白が不均一に見えることがあります。内側の角丸を余白に合わせて調整します。</p><a className="source" href="https://www.ui-skills.com/playbook/use-concentric-border-radius" target="_blank" rel="noreferrer">UI Skillsの解説<ArrowUpRight size={16}/></a></div><div className="radius-demo"><div className="radius-pair">{[false,true].map(correct=><div key={String(correct)}><div className="radius-outer" style={{padding}}><div style={{borderRadius:correct?32-padding:32}}><Plus size={22}/></div></div><span>{correct?'余白に合わせて調整':'同じ角丸を指定'}</span></div>)}</div><label>内側の余白 <output>{padding}px</output><input aria-label="角丸比較の内側の余白" type="range" min="4" max="24" step="2" value={padding} onChange={e=>setPadding(Number(e.target.value))}/></label><code>inner radius = 32 − {padding} = {32-padding}px</code></div></section>}
export default function Overview({go}){return <><section className="editorial-hero"><div className="hero-meta"><span>DESIGN SYSTEM FOR AI DEVELOPMENT</span><span>EDITION 02 / 2026</span></div><h1>Awesome<span>DS</span><i aria-hidden="true">↗</i></h1><div className="hero-bottom"><p>AI開発のための、<br/><strong>デザインシステムと実践知。</strong></p><div><p>文字、色、余白、コンポーネント、動き。<br/>選定の根拠を調べ、実装を試し、<br/>自分のプロダクトに取り入れる。</p><button className="primary" onClick={()=>document.getElementById('brand-lab').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}>デザインを試す<ArrowRight size={18}/></button></div><span className="hero-index" aria-hidden="true">A<span>↗</span></span></div></section><BrandLab/><section className="system-index"><div className="index-intro"><span className="eyebrow">THE FOUNDATIONS</span><h2>基本要素</h2><p>数値とルールを、<br/>実際の表示で確かめる。</p></div>{[['typography','Aa','Typography','日本語と英数字の組版'],['colors','●','Color','意味とコントラスト'],['foundations','▥','Layout','余白・角丸・密度'],['motion','↗','Motion','状態変化とフィードバック']].map(([id,symbol,en,ja])=><button className={'index-tile tile-'+id} key={id} onClick={()=>go(id)}><span className="tile-symbol" aria-hidden="true">{symbol}</span><div><h3>{en}</h3><p>{ja}</p></div><ArrowUpRight size={20}/></button>)}</section><RadiusStudy/><section className="research-section"><div className="section-top"><div><span className="eyebrow">03 / RESEARCH & DECISIONS</span><h2>参考資料と<br/>設計への反映</h2></div><button className="quiet" onClick={()=>go('knowledge')}>調査ノートを読む<ArrowUpRight size={18}/></button></div><div className="research-table">{studies.map(([n,name,title,desc,url])=><a key={name} href={url} target="_blank" rel="noreferrer"><span className="study-number">{n}</span><h3>{name}</h3><div><b>{title}</b><p>{desc}</p></div><ArrowUpRight size={20}/></a>)}</div><p className="research-disclosure">上記は各資料を参考にした独自の採用方針です。Nothingは本文の構成を確認済みで、画面の視覚検証は未完了です。</p></section><section className="skills-feature"><div><span className="eyebrow">04 / FROM DESIGN TO DEVELOPMENT</span><h2>開発に使う<br/>4つのSkills</h2><p>標準の適用、ブランド設計、デザイン検証、<br/>ユーザー体験の改善を支援します。</p><button className="primary" onClick={()=>go('skills')}>導入方法を見る<ArrowRight size={18}/></button></div><div className="skill-routes">{[['01','AwesomeDS','標準を適用'],['02','DS Creator','ブランドを設計'],['03','Design Verifier','実画面を検証'],['04','Design Thinking','利用体験を改善']].map(([n,name,desc])=><button key={n} onClick={()=>go('skills')}><span>{n}</span><div><b>{name}</b><small>{desc}</small></div><ArrowUpRight size={20}/></button>)}</div></section></>}
